### PR TITLE
Clean up distro references in README.md

### PR DESCRIPTION
**Pull request by pjreed**
This removes references to unsupported distributions and adds Kinetic
to the README file.

### CODE REVIEW

**Comment by evenator** [comment]
Let's just dump the builds table altogether.

**Comment by pjreed** [comment]
But what if somebody needs to know whether the ROS build farm successfully built the marti_perception_msgs on 32-bit Jade?

Yeah, I suppose it is not incredibly useful.

**Comment by pjreed** [comment]
I've removed the builds table and removed references to distro-specific branches (which never existed for `marti_messages` in the first place).

**Comment by evenator** [comment]
LGTM. Thanks for cleaning this up.

**Pull request merged**
