### PR TITLE
Add Wgs84Sample message type.

### PR DESCRIPTION
**Pull request by elliotjo**
This commit adds a new message type that contains a sensor measurement
in WGS-84 (e.g. GPS sample) and the corresponding sensor location in
relative coordinates (e.g. antenna position).

### CODE REVIEW

**Comment by evenator** [comment]
Is this meant to supersede sensor_msgs/NavSatFix? They seem to be mostly the same message with mostly the same use case, although this one isn't specific to satellite-based systems.

**Comment by elliotjo** [comment]
No, this is for further down a pipeline for a specific use case (basically
migrating a message from an internal package, pmm). This one has extra
information stripped out and adds the second point field for the sensor
location in relative space.  It is also meant to be more sat nav
independent because we can generate it from other sources like matching
sensor data to a priori maps.

**Comment by malban** [comment]
Maybe we can move this to a different package since this doesn't really represent a raw sensor message.

I suggest marti_nav_msgs since that is where the other map message is.  Also the ROS nav_msgs package contains Odometry, so this kind of matches that.

**Comment by elliotjo** [comment]
Moved to marti_nav_msgs.

**Comment by malban** [comment]
Looks good, can you squash these commits?

**Pull request merged**
