### PR TITLE
Add Messages For Autodocumentation

### PR DESCRIPTION
**Pull request by matt-attack**

### CODE REVIEW

**Comment by matt-attack** [comment]
@daniel-dsouza

**Comment by danthony06** [comment]
I like the idea, but I think we should put them in a separate package within marti_messages, like ```marti_messages/marti_introspection_msgs``` or something like that. The common messages are stamped versions of primitive types, so it's not the first place I would expect messages like this to go.

**Comment by matt-attack** [comment]
Works for me. Wasn't sure if it involved too much work to do that.

**Comment by matt-attack** [comment]
Updated to be in separate package.

**Review by danthony06 — APPROVED** [review]

**Pull request merged**
